version: '3'
services:
  db:
    image: mariadb:latest
    container_name: map-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "organdb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    networks:
      - main-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sangho/cofin-map:v1
    container_name: backend-map
    command: sh -c "dockerize -wait tcp://host.docker.internal:3306 -timeout 20s && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/backend-map/
    expose:
      - "8000"
    depends_on:
      - db
networks:
  main-network:
    driver: bridge