# Generated by Django 3.2.5 on 2021-11-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20211118_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='map',
            old_name='map_long',
            new_name='longitude',
        ),
    ]
