# Generated by Django 3.2.5 on 2021-11-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_auto_20211118_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='short_name',
            new_name='meta',
        ),
    ]
