# Generated by Django 3.1.8 on 2021-11-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_point_name', models.TextField()),
            ],
            options={
                'db_table': 'medpoint',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=4)),
                ('short_name', models.TextField()),
                ('name', models.TextField()),
                ('lat', models.TextField()),
                ('long', models.TextField()),
                ('total', models.IntegerField()),
                ('infected', models.IntegerField()),
                ('med_point_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.medpoint')),
            ],
            options={
                'db_table': 'maps',
            },
        ),
    ]
