# Generated by Django 3.2.5 on 2021-11-18 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20211116_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='cases',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='map',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='map',
            name='lat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='long',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='population',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='medpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
