# Generated by Django 3.2.5 on 2021-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20211118_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
